### ISSUE TITLE
Add side "buttons" to remaining page templates

### ISSUE THREAD

**Issue by jschumann** [wrdsb/wordpress-theme#85]

**Comment by suzannezc** [comment]
Can you explain what this is, please?

**Comment by jschumann** [comment]
Some of the page templates, when used as front pages, were missing the graphical links we force in the sidebar.

**Comment by suzannezc** [comment]
Because we are requesting schools only use the news as their home page, is this relevant any longer?

**Comment by suzannezc** [comment]
Closed with Procedure 4065: 5.2.8 

Since:
* All school sites must have news as their front page.
* Buttons only show on school sites.
* Buttons only show when news is the front page.
* News shows up using the home.php template when news is set to the front page

Therefore: 
* Buttons only need to be on the home.php template
